# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
pool:
  vmImage: ubuntu-latest
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: BrowserStackConfig@0
  inputs:
    BrowserStackServiceEndPoint: 'bstack-demo'
# - task: PythonScript@0
#   inputs:
#     scriptSource: 'inline'
#     script: |
#       pip install -r requirements.txt
#       paver run parallel
- task: CmdLine@2
  inputs:
    script: |
      pip install -r requirements.txt
      paver run parallel
- task: BrowserStackResults@1
  inputs:
    browserstackProduct: 'automate'
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'